Repository traPtitech/traQ_S-UI, pull requests merged in 2025-09, with the labels that each got.

#4787 fix(settings/stamp-palette): スタンプパレット作成/編集の二重作成/二重ダイアログ防止と離脱確認の安定化
  src/views/Settings/StampPaletteTab/StampPaletteCreateTab.vue
  src/views/Settings/StampPaletteTab/StampPaletteDetailTab.vue
Labels: bug

#4777 feat: メッセージ投稿時のプレビューに引用メッセージを表示できるようにする
  src/components/Main/MainView/MessageElement/MessageQuoteListItem.vue
  src/components/Main/MainView/MessageInput/MessageInput.vue
  src/components/Main/MainView/MessageInput/MessageInputPreview.vue
  src/store/domain/messagesView.ts
Labels: enhancement

#4778 feat: 検索結果に引用メッセージを表示できるようにする
  src/components/Main/CommandPalette/SearchResultMessageElement.vue
  src/components/Main/MainView/MessageElement/MessageQuoteList.vue
  src/components/Main/MainView/MessageElement/MessageQuoteListItem.vue
  src/components/Main/MainView/MessageElement/MessageQuoteListItemFooter.vue
Labels: enhancement

#4780 feat: 何度でも同じ引用メッセージにジャンプできるようにする
  src/components/Main/MainView/ChannelView/ChannelViewContent/ChannelViewContent.vue
  src/components/Main/MainView/MessageElement/MessageQuoteListItemFooter.vue
  src/components/UI/MessageLink.vue
  src/composables/dom/useRenderKey.ts
  src/composables/utils/useMessageQuery.ts
  src/store/ui/renderKeys.ts
  src/views/composables/useRouteWatcher.ts
Labels: bug

#4803 fix: MessageTools が複数表示されていた問題と非表示時にもクリック可能だった問題を修正
  src/components/Main/MainView/MessageElement/ClipElement.vue
  src/components/Main/MainView/MessageElement/MessageElement.vue
  src/components/Main/MainView/MessageElement/MessageTools.vue
  src/components/UI/ClickOutside.ts
Labels: bug

#4779 feat: メッセージ入力欄でのチャンネル名補完 (2)
  src/components/Main/MainView/MessageInput/DropdownSuggester/DropdownSuggester.vue
  src/components/Main/MainView/MessageInput/DropdownSuggester/DropdownSuggesterCandidate.vue
  src/components/Main/MainView/MessageInput/MessageInputTextArea.vue
  src/components/Main/MainView/MessageInput/composables/suggestion/overrides/channelSuggestion.ts
  src/components/Main/MainView/MessageInput/composables/suggestion/useSuggester.ts
  src/components/Main/MainView/MessageInput/composables/suggestion/useWordSuggester.ts
  src/components/Main/MainView/MessageInput/composables/suggestion/useWordSuggestionList.ts
  src/lib/basic/trieTree.ts
  src/lib/suggestion/applier.ts
  src/lib/suggestion/basic.ts
  tests/unit/lib/suggestion.spec.ts
Labels: enhancement

#4788 refactor: StampPalette.stamps の null ハンドリングを削除
  src/store/entities/stampPalettes.ts
Labels: refactor

#4809 fix: (開発環境下での) 警告を一部修正
  src/components/Main/MainView/ChannelView/ChannelHeader/ChannelHeaderChannelName.vue
  src/components/Main/MainView/ChannelView/ChannelHeader/ChannelHeaderRelationListItem.vue
  src/components/Main/MainView/ChannelView/ChannelHeader/composables/useCopyChannelLink.ts
  src/components/Main/MainView/ChannelView/ChannelViewContent/ChannelViewContentMain.vue
  src/components/Main/MainView/MessageElement/MessageQuoteListItem.vue
  src/components/Main/MainView/MessageElement/MessageQuoteListItemFooter.vue
  src/components/Main/MainView/MessageElement/StampElement.vue
  src/components/Main/MainView/MessageInput/composables/suggestion/useWordSuggestionList.ts
  src/components/Main/MainView/PrimaryViewSidebar/SidebarEvent/SidebarEventChildCreated.vue
  src/components/Main/MainView/PrimaryViewSidebar/SidebarEvent/SidebarEventParentChanged.vue
  src/components/Main/MainView/QallView/SubQallView.vue
  src/components/Main/NavigationBar/ChannelList/ChannelElement.vue
  src/components/Main/NavigationBar/DMChannelList/DMChannelElement.vue
  src/components/Main/NavigationBar/EphemeralNavigationContent/DraftList/DraftListDetailsPanelChannel.vue
  src/components/Main/NavigationBar/NavigationContent/ActivityElement.vue
  src/components/Main/NavigationBar/NavigationContent/ChannelsTab.vue
  src/components/Main/NavigationBar/NavigationContent/composables/useChannelFilter.ts
  src/components/Modal/ChannelManageModal/ChannelManageModal.vue
  src/components/Modal/FileModal/FileModalContentFooter.vue
  src/components/Modal/NotificationModal/NotificationModal.vue
  src/components/Modal/UserModal/FeatureContainer/LinkButtons.vue
  src/components/Modal/UserModal/ProfileTab/HomeChannel.vue
  src/components/Settings/BrowserTab/OpenMode.vue
  src/components/Settings/SessionTab/ViewStates.vue
  src/components/UI/MessagePanel/MessagePanel.vue
  src/composables/modal/useCanCreateChildChannel.ts
  src/composables/useChannelOptions.ts
  src/composables/useChannelPath.ts
  src/composables/useClose.ts
  src/store/entities/channels.ts
  src/store/ui/modal.ts
  src/views/composables/useRouteWatcher.ts
  tests/unit/composables/channels/useChannelPath.spec.ts
Labels: bug

#4813 fix: WebKit 系ブラウザでレイアウトが崩れる不具合を修正
  index.html
  src/App.vue
  src/components/Main/MainView/ChannelView/ChannelHeader/ChannelHeaderRelationListItem.vue
  src/components/Main/MainView/MainViewFrame.vue
  src/components/Main/MainView/MessagesScroller/MessagesScroller.vue
  src/components/Main/MainView/MessagesScroller/MessagesScrollerSeparator.vue
  src/components/Main/NavigationBar/NavigationContent.vue
  src/components/Main/StampPicker/StampPickerContainer.vue
  src/components/Modal/ModalContainer.vue
  src/components/UI/AIcon.vue
  src/lib/dom/browser.ts
  src/store/app/featureFlagSettings.ts
  src/views/MainPage.vue
Labels: iOS, patch

#4822 fix(stamp-list): 表示名に 0 幅スペース等が含まれる際にユーザ一覧のレイアウトが WebKit で崩れる問題を修正
  src/components/Main/MainView/MessageElement/StampDetailElementContent.vue
  src/lib/basic/string.ts
Labels: bug, iOS
